# Generated by Django 5.2.17 on 2026-08-15 16:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=160, unique=True, verbose_name="nombre"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="identificador"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "primary_color",
                    models.CharField(
                        default="#176247",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use un color hexadecimal como #176247.",
                                regex="^#[0-9a-fA-F]{6}$",
                            )
                        ],
                        verbose_name="color principal",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Bogota",
                        max_length=64,
                        verbose_name="zona horaria",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PlatformModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="código")),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "description",
                    models.CharField(blank=True, max_length=240, verbose_name="descripción"),
                ),
                (
                    "route_name",
                    models.CharField(max_length=80, verbose_name="nombre de ruta"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-solid fa-grid-2",
                        max_length=80,
                        verbose_name="icono",
                    ),
                ),
                (
                    "category",
                    models.CharField(default="Operación", max_length=80, verbose_name="categoría"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=100, verbose_name="orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "módulo de plataforma",
                "verbose_name_plural": "módulos de plataforma",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ClientDataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Base de sensores",
                        max_length=120,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "database_alias",
                    models.CharField(
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use entre 2 y 63 caracteres: letras minúsculas, números y guion bajo.",
                                regex="^[a-z][a-z0-9_]{1,62}$",
                            )
                        ],
                        verbose_name="alias de conexión",
                    ),
                ),
                (
                    "adapter_key",
                    models.CharField(
                        choices=[("aranet", "Aranet PostgreSQL")],
                        default="aranet",
                        max_length=40,
                        verbose_name="adaptador",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Opciones del adaptador. Nunca guarde contraseñas aquí.",
                        verbose_name="configuración no secreta",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_source",
                        to="core.client",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "fuente de datos",
                "verbose_name_plural": "fuentes de datos",
            },
        ),
        migrations.CreateModel(
            name="ClientMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Consulta"),
                            (20, "Operador"),
                            (30, "Administrador del cliente"),
                        ],
                        default=10,
                        verbose_name="nivel de acceso",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="core.client",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_membership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "membresía",
                "verbose_name_plural": "membresías",
                "ordering": ("client__name", "user__username"),
            },
        ),
        migrations.CreateModel(
            name="ClientModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="visible"),
                ),
                (
                    "minimum_access_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Consulta"),
                            (20, "Operador"),
                            (30, "Administrador del cliente"),
                        ],
                        default=10,
                        verbose_name="acceso mínimo",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_settings",
                        to="core.client",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_settings",
                        to="core.platformmodule",
                        verbose_name="módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "módulo habilitado",
                "verbose_name_plural": "módulos habilitados",
                "ordering": ("module__sort_order",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "module"),
                        name="unique_module_configuration_per_client",
                    )
                ],
            },
        ),
    ]
