# Generated by Django 5.2.17 on 2026-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0002_control_data_sensordata_alter_data_clave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('raw_message_id', models.BigIntegerField()),
                ('device_id', models.CharField(max_length=255)),
                ('event_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('sensor_1_soil_temperature_c', models.FloatField(blank=True, null=True)),
                ('sensor_1_soil_moisture_percent', models.FloatField(blank=True, null=True)),
                ('sensor_1_ec', models.FloatField(blank=True, null=True)),
                ('sensor_1_ph', models.FloatField(blank=True, null=True)),
                ('sensor_1_nitrogen', models.FloatField(blank=True, null=True)),
                ('sensor_1_phosphorus', models.FloatField(blank=True, null=True)),
                ('sensor_1_potassium', models.FloatField(blank=True, null=True)),
                ('sensor_1_salinity', models.FloatField(blank=True, null=True)),
                ('sensor_2_soil_temperature_c', models.FloatField(blank=True, null=True)),
                ('sensor_2_soil_moisture_percent', models.FloatField(blank=True, null=True)),
                ('sensor_2_ec', models.FloatField(blank=True, null=True)),
                ('sensor_2_ph', models.FloatField(blank=True, null=True)),
                ('sensor_2_nitrogen', models.FloatField(blank=True, null=True)),
                ('sensor_2_phosphorus', models.FloatField(blank=True, null=True)),
                ('sensor_2_potassium', models.FloatField(blank=True, null=True)),
                ('sensor_2_salinity', models.FloatField(blank=True, null=True)),
                ('air_temperature_c', models.FloatField(blank=True, null=True)),
                ('air_humidity_percent', models.FloatField(blank=True, null=True)),
                ('atmospheric_pressure_hpa', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('wind_direction_degree', models.FloatField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('solar_radiation_wm2', models.FloatField(blank=True, null=True)),
                ('illumination_klux', models.FloatField(blank=True, null=True)),
                ('sunshine_duration_h', models.FloatField(blank=True, null=True)),
                ('dew_point_temperature_c', models.FloatField(blank=True, null=True)),
                ('et0_mm', models.FloatField(blank=True, null=True)),
                ('level_temperature_c', models.FloatField(blank=True, null=True)),
                ('level_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"telemetry"."sensor_readings"',
                'managed': False,
            },
        ),
    ]
