# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models

import aplicaciones.satellite.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0005_sensor_configuration_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatelliteField",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="nombre")),
                (
                    "geometry",
                    models.JSONField(
                        help_text="GeoJSON Polygon en coordenadas WGS84 (longitud, latitud).",
                        validators=[aplicaciones.satellite.models.validate_polygon_geojson],
                        verbose_name="geometría",
                    ),
                ),
                (
                    "eosda_field_id",
                    models.PositiveBigIntegerField(blank=True, null=True, verbose_name="EOSDA field id"),
                ),
                (
                    "area_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="área (ha)",
                    ),
                ),
                ("crop_type", models.CharField(blank=True, max_length=120, verbose_name="cultivo")),
                ("sowing_date", models.DateField(blank=True, null=True, verbose_name="fecha de siembra")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="última sincronización"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satellite_fields",
                        to="core.client",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "lote satelital",
                "verbose_name_plural": "lotes satelitales",
                "ordering": ("client__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="SatelliteScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("eosda", "EOSDA")],
                        default="eosda",
                        max_length=20,
                        verbose_name="proveedor",
                    ),
                ),
                ("dataset", models.CharField(default="sentinel2l2a", max_length=80, verbose_name="dataset")),
                ("view_id", models.CharField(max_length=255, verbose_name="view id")),
                ("captured_at", models.DateTimeField(verbose_name="fecha de captura")),
                ("cloud_cover", models.FloatField(blank=True, null=True, verbose_name="nubosidad (%)")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadatos")),
                ("assets", models.JSONField(blank=True, default=dict, verbose_name="archivos")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="satellite.satellitefield",
                        verbose_name="lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "escena satelital",
                "verbose_name_plural": "escenas satelitales",
                "ordering": ("-captured_at",),
            },
        ),
        migrations.CreateModel(
            name="SatelliteMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("index_name", models.CharField(max_length=32, verbose_name="índice")),
                ("average", models.FloatField(blank=True, null=True, verbose_name="promedio")),
                ("minimum", models.FloatField(blank=True, null=True, verbose_name="mínimo")),
                ("maximum", models.FloatField(blank=True, null=True, verbose_name="máximo")),
                ("median", models.FloatField(blank=True, null=True, verbose_name="mediana")),
                ("p10", models.FloatField(blank=True, null=True, verbose_name="percentil 10")),
                ("p90", models.FloatField(blank=True, null=True, verbose_name="percentil 90")),
                ("stddev", models.FloatField(blank=True, null=True, verbose_name="desviación estándar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="satellite.satellitescene",
                        verbose_name="escena",
                    ),
                ),
            ],
            options={
                "verbose_name": "medición satelital",
                "verbose_name_plural": "mediciones satelitales",
                "ordering": ("scene__captured_at", "index_name"),
            },
        ),
        migrations.CreateModel(
            name="SatelliteJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("initial_sync", "Sincronización inicial"),
                            ("scene_search", "Búsqueda de escenas"),
                            ("statistics", "Estadísticas"),
                            ("imagery", "Imágenes"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutando"),
                            ("waiting_provider", "Esperando proveedor"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="estado",
                    ),
                ),
                ("provider_task_id", models.CharField(blank=True, max_length=255, verbose_name="task id del proveedor")),
                ("attempts", models.PositiveSmallIntegerField(default=0, verbose_name="intentos")),
                ("next_check_at", models.DateTimeField(blank=True, null=True, verbose_name="próxima consulta")),
                ("request_payload", models.JSONField(blank=True, default=dict, verbose_name="solicitud")),
                ("result_payload", models.JSONField(blank=True, default=dict, verbose_name="resultado")),
                ("error_message", models.TextField(blank=True, verbose_name="error")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="inicio")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="fin")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="satellite.satellitefield",
                        verbose_name="lote",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="satellite.satellitescene",
                        verbose_name="escena",
                    ),
                ),
            ],
            options={
                "verbose_name": "trabajo satelital",
                "verbose_name_plural": "trabajos satelitales",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="satellitefield",
            constraint=models.UniqueConstraint(
                fields=("client", "name"), name="unique_satellite_field_name_per_client"
            ),
        ),
        migrations.AddConstraint(
            model_name="satellitefield",
            constraint=models.UniqueConstraint(
                fields=("client", "eosda_field_id"), name="unique_eosda_field_per_client"
            ),
        ),
        migrations.AddIndex(
            model_name="satellitescene",
            index=models.Index(fields=["field", "-captured_at"], name="sat_scene_field_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="satellitescene",
            constraint=models.UniqueConstraint(
                fields=("field", "dataset", "view_id"), name="unique_satellite_scene_per_field"
            ),
        ),
        migrations.AddIndex(
            model_name="satellitemeasurement",
            index=models.Index(fields=["index_name"], name="sat_measure_index_idx"),
        ),
        migrations.AddConstraint(
            model_name="satellitemeasurement",
            constraint=models.UniqueConstraint(
                fields=("scene", "index_name"), name="unique_satellite_measurement_per_scene"
            ),
        ),
        migrations.AddIndex(
            model_name="satellitejob",
            index=models.Index(fields=["status", "next_check_at"], name="sat_job_status_next_idx"),
        ),
        migrations.AddIndex(
            model_name="satellitejob",
            index=models.Index(fields=["field", "status"], name="sat_job_field_status_idx"),
        ),
    ]
